# Generated by Django 5.1.7 on 2025-03-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField()),
                ('pages', models.IntegerField()),
            ],
        ),
    ]
