# Generated by Django 5.2 on 2025-04-15 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0004_user_result'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
